version: "3"

services:
    app:
        build: .
        restart: always
        environment:
            REALM: prod
            GUNICORN_CMD_ARGS: "--log-level debug --error-logfile '-' --access-logfile '-'"
            REDIS_URL: "//redis:6379"
            SESSION_SECRET_KEY: "${SESSION_SECRET_KEY:?specify SESSION_SECRET_KEY in .env file}"
        links:
            - redis
        ports:
            - "8000:8000"

    redis:
        image: redis
        restart: always
